### ISSUE TITLE
Add Angular 8 support

### ISSUE THREAD

**Issue by georgique** [exportarts/ngx-cookie-banner#2]
Since Angular 8 is currently active, would it take much effort to add it's support?

**Comment by HelainSchoonjans** [comment]
+1! I upgraded some applications to Angular 8 and Angular2-cookie-consent is no more maintained...

**Comment by evolkmann** [comment]
Hi @georgique, @HelainSchoonjans,
the package currently lists Angular 8 as a peer dependency:
https://github.com/exportarts/ngx-cookie-banner/blob/daa60c17b6a457d7c5a49a1d79287787eb88c0ba/projects/ngx-cookie-banner/package.json#L5-L6

Can you please elaborate which issues you have with Angular 8 when using the package?
Thanks, Enzo

**Comment by evolkmann** [comment]
@georgique @HelainSchoonjans 
Please have a look at PR #5. I explicitly tested with ng8 but did not find any issues (besides disabling ivy after the ng9 update). Would be great if you could have a look at that and verify that there are no issues.
Thanks, Enzo

**Comment by georgique** [comment]
Thanks @evolkmann, most likely I won't be able to help here - needed solution quickly and switched to another lib.

**Comment by evolkmann** [comment]
@georgique Thanks for your feedback. I would still be interested in the kind of issues you had with this library, just to understand the original problem.

**Comment by georgique** [comment]
@evolkmann I absolutely had no issues other than that it wasn't declared compatible with Angular 8, only 9. I couldn't install it via npm, that's all.

**Comment by evolkmann** [comment]
Closing this as #5 has been merged.
