### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by shauke** [exportarts/ngx-cookie-banner#48]
Could you please provide any licensing information for this library, e.g. MIT or alike.

**Comment by evolkmann** [comment]
Hi @shauke, sure. I forgot to add this. It is now MIT :)

**Comment by shauke** [comment]
This was fast. :) Thanks a lot.

**Comment by evolkmann** [comment]
I also updated to v0.1.1 and fixed the license field in the package.json, so you also have the info locally in the project
